## 设置用户 设置ssh 准备发布文件夹 初始化git
---
- name: ensure application group
  group:
    name: "{{ application_group }}"

- name: ensure application user
  user:
    name: "{{ application_user }}"
    group: "{{ application_group }}"

- name: ensure .ssh directory for application user
  file:
    path: "{{ application_user_home }}/.ssh"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0700

- name: add id_rsa
  copy:
    dest: "{{ application_user_home }}/.ssh/id_rsa"
    content: "{{ lookup('file', 'ssh/id_rsa') }}"
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
    mode: 0600
#
#- name: add gitlab to known hosts
#  known_hosts:
#    name: code.aihuishou.com
#    key: "{{ lookup('file', 'id_rsa.pub') }}"
#  become: true
#  become_user: "{{ application_user }}"

- name: ensure directory for code distribution
  file:
    path: "{{ distribution_path }}"
    state: directory
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
  sudo: true
