version: '3'
services:
  php:
    build: ./
    ports:
      - "9000:9000"
    volumes:
      - ./:/www
      - ./conf:/usr/local/etc/php
      - ./logs:/phplogs
  nginx:
    build: ../nginx
    volumes:
      - ./:/www
    ports:
      - "8012:80"