---
- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: ppastable

- name: Install Nginx
  apt: pkg=nginx state=latest update_cache=true
  when: ppastable|success
  register: nginxinstalled
  notify:
   - Start Nginx

- name: Install Unzip
  apt: pkg=unzip state=latest update_cache=true