# 重启 reload php nginx  迁移数据库，重启任务 重启定时 重启 supervisord
- name: run migrations
  shell: php artisan migrate --force
  args:
    chdir: "{{ application_path }}"
  become: true
  become_user: "{{ application_user }}"
  when: jobserver


- name: restart php-fpm service if release version is changed
  shell: sudo service php{{ php_version }}-fpm restart
  sudo: true

- name: restart jobs gracefully if release version is changed
  shell: php artisan queue:restart
  args:
    chdir: "{{ application_path }}"
  become: true
  become_user: "{{ application_user }}"

- name: add Kernel into crontab
  cron:
    name:  "add laravel into crontab"
    user: "{{ application_user }}"
    job: "/usr/bin/php {{ application_path }}/artisan schedule:run 1>> {{ crontab_logfile }} 2>&1"
  when: jobserver
  sudo: true

#- name: add url Kernel into crontab
#  cron:
#    name:  "add laravel into crontab"
#    user: "{{ application_user }}"
#    job: "/usr/bin/php {{ url_application_path }}/artisan schedule:run 1>> {{ url_crontab_logfile }} 2>&1"
#  when: jobserver
#  sudo: true

- name: setup supervisord config file
  template:
    src: supervisord.conf.j2
    dest: "{{ supervisor_path }}/supervisord.conf"
    backup: true
    owner: "{{ application_user }}"
    group: "{{ application_group }}"
  sudo: true
#- name: conf supervisord
#  supervisorctl:
#    name: my_app
#    state: restarted
#    config: "{{ supervisor_path }}/supervisord.conf"
#  args:
#    chdir: "{{ supervisor_path }}"
- name: conf supervisord
  shell: " {{ supervisor_path }}/venv/bin/supervisord -c {{ supervisor_path }}/supervisord.conf"
  args:
    chdir: "{{ supervisor_path }}"
  sudo: true
  ignore_errors: true
- name: stop supervisord
  shell: "{{ supervisor_path }}/venv/bin/supervisorctl  -c {{ supervisor_path }}/supervisord.conf  stop all"
  args:
    chdir: "{{ supervisor_path }}"
  sudo: true
- name: reload supervisord
  shell: "{{ supervisor_path }}/venv/bin/supervisorctl  -c {{ supervisor_path }}/supervisord.conf  reload"
  args:
    chdir: "{{ supervisor_path }}"
  sudo: true
- name: start supervisord
  shell: "{{ supervisor_path }}/venv/bin/supervisorctl  -c {{ supervisor_path }}/supervisord.conf  start all"
  args:
    chdir: "{{ supervisor_path }}"
  sudo: true
#- name: reload supervisord
#  shell: "sudo ps aux|grep supervisord|awk {'print $2'} | sed -e 's/^/kill -9 /g'|sudo sh"
# shell: "sudo ps aux|grep artisan|awk {'print $2'} | sed -e 's/^/kill -9 /g'|sudo sh"
#  args:
#    chdir: "{{ supervisor_path }}"
#  sudo: true
#  ignore_errors: true



