---
 - hosts: webservers
   become: yes
   user: root
   roles:
    - prepare
    - git
    - nginx
    - php
    - redis
    - supervisor
    - webserver
    - distribution
    - distribution-url
    - reload